// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CloseTabsToRight
{
    static class Vsix
    {
        public const string Id = "9A182C3F-C860-46F9-8638-15F6D22BD426";
        public const string Name = "Close Tabs To Right";
        public const string Description = @"Close document tabs to the right of the current document.";
        public const string Language = "en-US";
        public const string Version = "1.5";
        public const string Author = "Evan Kinney";
        public const string Tags = "close, tab, tabs, to, right, document";
    }
}
